Feature/java 21
companieshouse/extensions-api pull request #126
Opened 2023-12-01 16:35 UTC by vaibhavcompanieshouse

2023-12-04 17:33 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-01-05 10:38 UTC, bcullerton requested changes

2024-01-05 10:38 UTC, bcullerton commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine -->
Can this be removed

2024-01-05 10:38 UTC, bcullerton commented on pom.xml
> +        <version>2.1.2</version>
Can this be updated to 2.1.5

2024-01-05 10:38 UTC, bcullerton commented on Makefile
> +.PHONY: build-image
Is this still needed?

2024-01-05 10:38 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/extensions/api/config/HealthCheckController.java
> +}
Not a big deal but going forwards could we take a look at using spring-boot-actuator for healthchecks if they aren't present. Saves on having to write out the classes

2024-01-05 10:38 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/extensions/api/requests/RequestsController.java
> +import org.springframework.web.bind.annotation.*;
star import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/attachments/AttachmentsServiceUnitTest.java
> +import static org.mockito.Mockito.*;
star imports here

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/attachments/file/FileTransferApiClientUnitTest.java
> +import org.springframework.http.*;
stars here

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/authorization/CompanyAuthorizationInterceptorTest.java
> +import static org.mockito.Mockito.*;
star import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/logger/ApiLoggerTest.java
> +import static org.mockito.Mockito.*;
star import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/reasons/ReasonServiceUnitTest.java
> +import static uk.gov.companieshouse.extensions.api.Utils.Utils.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/reasons/ReasonsControllerUnitTest.java
> +import static uk.gov.companieshouse.extensions.api.Utils.Utils.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/requests/MongoDBTest.java
> +import org.junit.jupiter.api.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/requests/RequestControllerUnitTest.java
> +import static uk.gov.companieshouse.extensions.api.Utils.Utils.*;
.* imports

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/requests/RequestMapperUnitTest.java
> +import static uk.gov.companieshouse.extensions.api.Utils.Utils.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/requests/RequestRepositoryIntegrationTest.java
> +import static org.junit.jupiter.api.Assertions.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/requests/RequestServiceUnitTest.java
> +import static uk.gov.companieshouse.extensions.api.Utils.Utils.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/attachments/AttachmentsControllerUnitTest.java
> +import static org.mockito.ArgumentMatchers.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/attachments/file/FileTransferGatewayIntegrationTest.java
> +import static org.junit.jupiter.api.Assertions.*;
.* import

2024-01-05 10:38 UTC, bcullerton commented on src/test/java/uk/gov/companieshouse/extensions/api/attachments/file/FileTransferGatewayMockIntegrationTest.java
> +import org.junit.jupiter.api.*;
.* import

2024-01-05 16:11 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-01-11 13:45 UTC, bcullerton approved these changes

2024-01-11 14:30 UTC, merged